blu3print:
  max-scale: 10 # Maximum scale of a Blu3Print
  max-size: 100 # Maximum size of a Blu3Print
  max-overall-size: 200 # Maximum size * scale of a Blu3Print
  cooldown: 500 # Cooldown in ms between two Blu3print usages
  hologram-ttl: 10 # Time in seconds until a hologram disappears after being placed
  recipe: # Recipe for crafting a Blu3Print
    ingredients:
      - PAPER
      - LAPIS_LAZULI
      - FEATHER
  ignored-materials: # Materials to ignore when building / placing blu3prints
    - AIR
    - WATER
    - LAVA
  placement:
    alignment: center # left / center / right
    relative: true  # true / false  -  should place from direction player facing
  messaging: # Fine tune messaging for the Blu3Print plugin
    free-placement-message:
      enabled: true
    force-placement-message:
      enabled: true
    discount-placement-message:
      enabled: true
    update-available-message:
      enabled: true
    cooldown-message:
      enabled: false
  logging: # Fine tune logging for the Blu3Print plugin
    verbose: false # Enable verbose logging
    imported-blu3prints: # Log all imported blu3prints
      enabled: false
    update-level: PATCH # MAJOR / MINOR / PATCH / NONE  -  minimum level of updates to log
  update-check-interval: 24 # Check for updates every X hours
    