blu3print:
  max-scale: 10 # Maximum scale of a Blu3Print
  max-size: 100 # Maximum size of a Blu3Print
  max-overall-size: 200 # Maximum size * scale of a Blu3Print
  cooldown: 500 # Cooldown in ms between two Blu3print usages
  hologram-ttl: 10 # Time in seconds until a hologram disappears after being placed
  recipe: # Recipe for crafting a Blu3Print
    ingredients:
      - PAPER
      - LAPIS_LAZULI
      - FEATHER
  ignored-materials: # Materials to ignore when building / placing blu3prints
    - AIR
    - WATER
    - LAVA
  messaging: # Fine tune messaging for the Blu3Print plugin
    free-placement-message:
      enabled: true
    force-placement-message:
      enabled: true
    discount-placement-message:
      enabled: true
    